#### 导入pytorch 创建一个5*3的未初始化的Tensor

In [2]:
import torch
x = torch.empty(5,3)
print(x)

tensor([[1.5654e-14, 4.5843e-41, 4.4153e-16],
        [4.5843e-41, 1.5693e-14, 4.5843e-41],
        [4.4153e-16, 4.5843e-41, 6.2962e-16],
        [4.5843e-41, 6.5208e-16, 4.5843e-41],
        [3.4441e-16, 4.5843e-41, 7.5000e-34]])


#### 创建一个5*3的随机初始化的Tensor

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.6334, 0.0577, 0.4755],
        [0.3590, 0.7183, 0.1135],
        [0.2866, 0.4006, 0.8603],
        [0.7946, 0.6642, 0.1554],
        [0.1753, 0.9028, 0.3505]])


##### 创建一个5*3的Long型全0的tensor

In [3]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


##### 直接根据数据创建

In [5]:
x  = torch. tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


##### 通过现有的张量来创建

In [6]:
x = x.new_ones(5,3, dtype = torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


##### 指定新的数据类型

In [7]:
x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[ 0.7649, -1.5030, -1.8745],
        [ 0.3803, -0.3920,  0.4211],
        [ 0.1336,  0.3140,  2.0072],
        [-1.0361, -0.3115, -1.1644],
        [-1.0737,  0.5793, -0.3550]])


##### 通过shape或者size()获取tensor的形状

In [8]:
print(x.shape)

torch.Size([5, 3])


In [10]:
print(x.size())

torch.Size([5, 3])


In [12]:
x = torch.tensor(3)
print(x)

tensor(3)


### 算数操作

In [13]:
y = torch.rand(5,3)
print(y)

tensor([[0.5983, 0.0681, 0.9356],
        [0.8551, 0.7306, 0.4612],
        [0.8593, 0.4644, 0.1718],
        [0.3114, 0.9647, 0.7545],
        [0.4996, 0.0322, 0.0550]])


In [14]:
print(x+y)

tensor([[3.5983, 3.0681, 3.9356],
        [3.8551, 3.7306, 3.4612],
        [3.8593, 3.4644, 3.1718],
        [3.3114, 3.9647, 3.7545],
        [3.4996, 3.0322, 3.0550]])


In [15]:
print(torch.add(x,y))

tensor([[3.5983, 3.0681, 3.9356],
        [3.8551, 3.7306, 3.4612],
        [3.8593, 3.4644, 3.1718],
        [3.3114, 3.9647, 3.7545],
        [3.4996, 3.0322, 3.0550]])


### 指定输出

In [16]:
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[3.5983, 3.0681, 3.9356],
        [3.8551, 3.7306, 3.4612],
        [3.8593, 3.4644, 3.1718],
        [3.3114, 3.9647, 3.7545],
        [3.4996, 3.0322, 3.0550]])


### 加法形式3 Inplace

In [17]:
y.add(x)
print(y)

tensor([[0.5983, 0.0681, 0.9356],
        [0.8551, 0.7306, 0.4612],
        [0.8593, 0.4644, 0.1718],
        [0.3114, 0.9647, 0.7545],
        [0.4996, 0.0322, 0.0550]])


In [ ]:
x = torch.rand(5,3)
print(x)

### 索引简介 https://blog.csdn.net/weicao1990/article/details/93599947
注意索引出来的结果与原数据共享内存，修改一个，另一个也会随之修改

In [34]:
y = x[0,:]
print(y)
y += 1
print(y)
print(x[0,:])

tensor([0.1388, 0.9421, 0.7220])
tensor([1.1388, 1.9421, 1.7220])
tensor([1.1388, 1.9421, 1.7220])


### 改变tensor的形状

#### view 仅仅改变了观察角度 原来的x并不改变 但是此时y如果改变 x也跟着 改变

In [ ]:
x = torch.randn(5,3)
print(x)

In [39]:
y = x.view(15)
print(y)
print(x)

tensor([ 0.3065,  0.1866, -0.3121, -0.4429,  0.5370, -0.4866,  0.8355, -1.0194,
         1.0904, -0.4463, -1.0890,  1.1894,  1.0868,  0.6955,  0.8297])
tensor([[ 0.3065,  0.1866, -0.3121],
        [-0.4429,  0.5370, -0.4866],
        [ 0.8355, -1.0194,  1.0904],
        [-0.4463, -1.0890,  1.1894],
        [ 1.0868,  0.6955,  0.8297]])


### 如果想要一个真正的副本

In [40]:
x_cp = x.clone().view(15)
x -= x
print(x)
print(x_cp)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([ 0.3065,  0.1866, -0.3121, -0.4429,  0.5370, -0.4866,  0.8355, -1.0194,
         1.0904, -0.4463, -1.0890,  1.1894,  1.0868,  0.6955,  0.8297])


#### 函数item()

In [45]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.4124])
0.4123568832874298


### 广播机制

In [46]:
x = torch.arange(1,3).view(1,2)
y = torch.arange(1,4).view(3,1)
print(x)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


#### torch.arange() 返回一维张量

In [51]:
tensor = torch.ones(2, dtype=torch.int8)
print(tensor)

tensor([1, 1], dtype=torch.int8)


### tensor 和 numpy 相互转换

In [62]:
import numpy 
x = torch.ones(5)
y = x.numpy()
print(x,y)

x = numpy.ones(5)
y = torch.tensor(x)
print(x,y)

x = numpy.ones(5)
y = torch.from_numpy(x)
print(x,y)
x += 1
print(x,y)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### 矢量相加

In [65]:
a = torch.ones(10)
b = torch.ones(10)
d = a + b
print(d)

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])
